version: 2
jobs:
  build:
    working_directory: ~/app
    machine:
      image: circleci/classic:latest
      timezone: Europe/Zagreb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-docker-{{ .Branch }}
      - run:
          name: Load Docker layers cache
          command: |
            set +o pipefail
            docker load -i ~/docker-layers.tar | true
      - run:
          name: Build application Docker image
          command: |
            export IMAGE_TAG=$CIRCLE_SHA1
            docker build -t chainsafe/lodestar:${IMAGE_TAG} -f ./docker/Dockerfile .
      - run:
          name: Tag docker image as latest
          command: |
            docker tag chainsafe/lodestar:${IMAGE_TAG} chainsafe/lodestar:latest
      - run:
          name: Push docker image to docker hub
          command: |
            docker push chainsafe/lodestar:${IMAGE_TAG} chainsafe/lodestar:latest
      - run:
          name: Save docker layers cache
          command: |
            docker save -o ~/docker-layers.tar chainsafe/lodestar:${IMAGE_TAG}
      - save_cache:
          key: v1-docker-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/docker-layers.tar
workflows:
  version: 2
  build:
    jobs:
      - build